import Foundation
let temporary = FileManager.default.temporaryDirectory.appendingPathComponent("mimo-install-" + UUID().uuidString)
let root = temporary.appendingPathComponent(".mimocode/boring-notch-bridge")
defer { try? FileManager.default.removeItem(at: temporary) }
let source = URL(fileURLWithPath: FileManager.default.currentDirectoryPath).appendingPathComponent("Integrations/MiMoDesktop")
precondition(MiMoBridgeClient.install(sourceURL: source, destinationRoot: root) == "installed")
let configURL = root.appendingPathComponent("config.json")
let data = try Data(contentsOf: configURL)
let info = try FileManager.default.attributesOfItem(atPath: configURL.path)
precondition((info[.posixPermissions] as! NSNumber).intValue == 0o600)
precondition(MiMoBridgeClient.install(sourceURL: source, destinationRoot: root) == "installed")
let installedAgain = try Data(contentsOf: configURL)
precondition(installedAgain == data)
let plugin = root.deletingLastPathComponent().appendingPathComponent("plugins/boring-notch.js")
try Data("foreign plugin".utf8).write(to: plugin)
precondition(MiMoBridgeClient.install(sourceURL: source, destinationRoot: root) == "conflict")
let contents = try String(contentsOf: plugin, encoding: .utf8)
precondition(contents == "foreign plugin")
print("PASS: MiMo component install, private pairing, idempotency and foreign-file preservation")
