import Foundation
func task(_ status: CodexDisplayStatus, _ messageID: String = "reply1") -> CodexPinnedTask {
    CodexPinnedTask(id: "task", title: "", status: status, latestReply: "", messages: [CodexTaskMessage(id: messageID, role: .assistant, text: "", phase: "final")])
}
var tracker = CodexUnreadTracker()
precondition(tracker.update([task(.completed)]).isEmpty)
precondition(tracker.unreadIDs.isEmpty)
precondition(tracker.update([task(.running)]).isEmpty)
precondition(tracker.update([task(.completed, "reply2")]) == ["task"])
precondition(tracker.unreadIDs == ["task"])
precondition(tracker.update([task(.completed, "reply2")]).isEmpty)
tracker.markRead("task")
precondition(tracker.unreadIDs.isEmpty)
precondition(tracker.update([task(.completed, "reply2")]).isEmpty)
precondition(tracker.update([task(.completed, "reply3")]) == ["task"])
let saved = try JSONEncoder().encode(tracker)
tracker = try JSONDecoder().decode(CodexUnreadTracker.self, from: saved)
precondition(tracker.unreadIDs == ["task"])
precondition(tracker.update([task(.completed, "reply3")], readingID: "task").isEmpty)
precondition(tracker.unreadIDs.isEmpty)
precondition(tracker.update([task(.completed, "reply4")], readingID: "task").isEmpty)
precondition(tracker.update([]).isEmpty)
precondition(tracker.unreadIDs.isEmpty)
print("PASS: baseline, new completion, repeat refresh, read, next reply, restart, viewing, removal")
